---
title: "Support Vector Machine"
author: "Jeffrey Y.C. Liu"
output: pdf_document
---

##Support Vector Classifier
## Code Chunk 1
```{r}
set.seed(1)
x=matrix(rnorm(20*2),ncol=2)
x
y = c(rep(-1,10),rep(1,10))
y
```

## Code Chunk 2
```{r}
x[y==1,]=x[y==1,]+1
x
plot(x,col=(3-y))
dat = data.frame(x=x, y = as.factor(y))
```


## Code Chunk 3
```{r}
library(e1071)

svcfit=svm(y~.,data = dat, kernel = "linear", cost=10,scale = FALSE)

plot(svcfit, dat)

svcfit$index

summary(svcfit)
```

## Code Chunk 4
```{r}
svcfit=svm(y~.,data = dat, kernel = "linear", cost=0.1, scale = FALSE)

plot(svcfit, dat)

svcfit$index
```

## Cross-Validation to find cost
## Code Chunk 5
```{r}
set.seed(1)

tune.out = tune(svm,y~.,data = dat, kernel = "linear", ranges = list(cost = c(0.001, 0.01, 0.1, 1, 5, 10, 100)))

summary(tune.out)

bestmod = tune.out$best.model

summary(bestmod)
```


## Code Chunk 6
```{r}
xtest = matrix(rnorm(20*2), ncol=2)

ytest = sample(c(-1,1), 20, rep = TRUE)

xtest[ytest==1,] = xtest[ytest==1,] + 1

testdat = data.frame(x=xtest, y=as.factor(ytest))

ypred=predict(bestmod,testdat)

table(predict=ypred,truth=testdat$y)
```

## Code Chunk 7
```{r}
svcfit=svm(y~.,data = dat, kernel = "linear", cost =0.01, scale = FALSE)

ypred = predict(svcfit,testdat)

table(predict = ypred, truth = testdat$y)
```

## Code Chunk 8
```{r}
x[y==1,] = x[y==1,]+0.5

plot(x, col=(y+5)/2,pch=19)

dat = data.frame(x=x,y=as.factor(y))

svcfit=svm(y~., data = dat, kernel = "linear", cost = 1e5)

summary(svcfit)

plot(svcfit,dat)

```

## Support Vector Machine
## Code Chunk 9
```{r}
set.seed(1)

x = matrix(rnorm(200*2), ncol = 2)

x[1:100,] = x [1:100,] + 2

x[101:150,] = x[101:150,] -2

y = c(rep(1,150),rep(2,50))

dat = data.frame(x = x, y = as.factor(y))

plot(x, col=y)
```

## Code Chunk 10
```{r}
train = sample(200, 100)

svmfit = svm(y~., data = dat[train,], kernel ="radial", gamma = 1, cost = 1)

plot(svmfit, dat[train,])

summary(svmfit)
```

## Code Chunk 11
```{r}
svmfit = svm(y~., data = dat[train,], kernel ="radial", gamma = 1, cost = 1e5)

plot(svmfit, dat[train,])
```

## Code Chunk 12
```{r}
set.seed(1)

tune.out = tune(svm, y~., data = dat[train,], kernel = "radial", ranges=list(cost=c(0.1,1,10,100,1000), gamma=c(0.5,1,2,3,4)))

summary(tune.out)

table(true = dat[-train,"y"], predicted = predict(tune.out$best.model, newdata = dat[-train,]))
```
